# Generated by Django 2.1.2 on 2018-11-01 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Back', '0002_usuario_perfil'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='perfil',
        ),
        migrations.AlterField(
            model_name='usuario',
            name='id',
            field=models.AutoField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
