# Generated by Django 2.1.2 on 2018-11-05 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Back', '0003_auto_20181101_1812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
